### ISSUE TITLE
oAuth Implementation (web)

### ISSUE THREAD

**Issue by mooyg** [mooyg/locus#6]
Implement oAuth for the web in `packages/web/src/pages/login`

Use the previous component and have links accordingly

**Comment by muskdevbugged** [comment]
var http  = require('http'),
    sys   = require('sys'),
    URL   = require('url'),
    OAuth = require('oauth').OAuth;

var oa= new OAuth('https://api.twitter.com/oauth/request_token',
                  'https://api.twitter.com/oauth/access_token',
                  'TWITTER_CONSUMER_KEY',
                  'TWITTER_CONUSMER_SECRET',
                  '1.0',
                  null,
                  'HMAC-SHA1');

var callbackUrl = 'http://127.0.0.1:3000/auth/twitter/callback';
var global_oauth_token = {};
var global_oauth_token_secret = {};

http.createServer(function (req, res) {

  var reqURL = URL.parse(req.url);
  switch (reqURL['pathname']) {

    case '/': 
      console.log('Default URL');
      oa.getOAuthRequestToken(function(error, oauth_token, oauth_token_secret, results){
        if(error) {
          console.log('error :' + sys.inspect(error));
          var errResponse = 'Unable to retrieve request token';
          res.writeHead(200, {'Content-Type': 'text/plain', 'Content-Length': errResponse.length});
          res.end(errResponse);
        }
        else {
          console.log('oauth_token: ' + oauth_token);
          console.log('oauth_token_secret: ' + oauth_token_secret);
          console.log('requestoken results: ' + sys.inspect(results));


          global_oauth_token = oauth_token;
          global_oauth_token_secret = oauth_token_secret;
          
       
          var twitterAuthEndpoint = 'https://api.twitter.com/oauth/authenticate?oauth_token=' + oauth_token;
          console.log('Redirecting to ' + twitterAuthEndpoint);
          res.writeHead(301, {'Content-Type': 'text/plain', 'Location': twitterAuthEndpoint});
          res.end('Redirecting...\n');
        }
      });
      break;

    case callbackUrl: 
      console.log('http://127.0.0.1:3000/auth/twitter/callback');

 
      oa.getOAuthAccessToken(global_oauth_token, global_oauth_token_secret, function(error, oauth_access_token, oauth_access_token_secret, results) {
        console.log('Requested access token');
        console.log('oauth_access_token: ' + oauth_access_token);
        console.log('oauth_token_secret: ' + oauth_access_token_secret);
        console.log('accesstoken results: ' + sys.inspect(results));

        var stringifiedResults = JSON.stringify(results);
        res.writeHead(200, {'Content-Type': 'text/plain', 'Content-Length': stringifiedResults.length});
        res.end(stringifiedResults);
      });
      break;
  }
}).listen(8888, '127.0.0.1');
console.log('Server running at http://127.0.0.1:8888/');
